// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFiUwyUCm5LxJkxxarlhOKlm61F3ely4c',
    appId: '1:344325722747:web:25d35950a0efc8d38808de',
    messagingSenderId: '344325722747',
    projectId: 'blackcoffer-b7920',
    authDomain: 'blackcoffer-b7920.firebaseapp.com',
    storageBucket: 'blackcoffer-b7920.appspot.com',
    measurementId: 'G-C1YMW0DX35',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUostJJ1cWRKC1l6kYqSTsN1lyFwfDbqs',
    appId: '1:344325722747:android:4f29c54332809eff8808de',
    messagingSenderId: '344325722747',
    projectId: 'blackcoffer-b7920',
    storageBucket: 'blackcoffer-b7920.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAI5q2C0jTB2YzppvSl67_d_DV4vYqLbbA',
    appId: '1:344325722747:ios:f00d53306fd28df18808de',
    messagingSenderId: '344325722747',
    projectId: 'blackcoffer-b7920',
    storageBucket: 'blackcoffer-b7920.appspot.com',
    iosBundleId: 'com.assignmentoffer.assignment',
  );
}
